homeassistant:
  name: Domek
  latitude: 50.35061
  longitude: 18.91458
  elevation: 278
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml
frontend:

#introduction:

config:

http:
  server_port: 443
  base_url: www.chatabarta.pl
  api_password: !include secret.yaml
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


#updater:

discovery:

recorder:
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    entities:
      - sensor.since_last_boot

conversation:

history:

logbook:
  exclude:
    domains:
      - automation

sun:

#weather:
#  - platform: openweathermap
#    api_key: bd0dc2fae998ca753d326a1b1a68f193

mqtt:
  broker: 127.0.0.1

light:
  - platform: hyperion
    host: 192.168.1.29

sensor: !include sensor.yaml

switch: !include switch.yaml

media_player: !include media_player.yaml

notify: !include notify.yaml

device_tracker: !include device_tracker.yaml

group: !include groups.yaml

automation: !include automations.yaml

weblink: !include weblink.yaml

hassio:

arduino:
  port: /dev/ttyUSB0

# Text to speech
#tts:
#  - platform: google

#android_ip_webcam:
#  - host: 192.168.1.18

#camera:
#  - platform: generic
#    name: Monitoring
#    still_image_url: http://192.168.1.18:8080/photoaf.jpg
