homeassistant:
  name: Domek
  latitude: 50.35061
  longitude: 18.91458
  elevation: 278
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml

#introduction:

frontend:

config:

http:
  api_password: !include secret.yaml

#updater:

discovery:

#conversation:

history:

logbook:

sun:

weather:
  - platform: openweathermap
    api_key: bd0dc2fae998ca753d326a1b1a68f193

mqtt:
  broker: 127.0.0.1
  
light:
  - platform: hyperion
    host: 192.168.1.29

sensor: !include sensor.yaml

switch: !include switch.yaml

media_player:
  - platform: webostv
    name: Telewizor
    host: 192.168.1.13
    mac: C8:08:E9:EC:FE:E5
    customize:
      sources:
        - livetv
        - youtube
        - netflix
        - HDMI2
  - platform: spotify
    client_id: e40f3abe28b2457bb288fa1ac9a2da9a
    client_secret: 1e0e4ea0ffb548e3bc1fa7c0b245a6f1       

notify:
  - platform: webostv
    host: 192.168.1.13
    name: Telewizor

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.10
      - 192.168.1.17
    home_interval: 5
# Text to speech
#tts:
#  - platform: google

#android_ip_webcam:
#  - host: 192.168.1.18

camera:
  - platform: generic
    name: Monitoring
    still_image_url: http://192.168.1.18:8080/photoaf.jpg

group: !include groups.yaml

automation: !include automations.yaml
