- platform: webostv
  name: Telewizor
  host: 192.168.1.13
  mac: C8:08:E9:EC:FE:E5
  customize:
    sources:
      - livetv
      - youtube
      - netflix
      - HDMI2
- platform: spotify
  client_id: e40f3abe28b2457bb288fa1ac9a2da9a
  client_secret: 1e0e4ea0ffb548e3bc1fa7c0b245a6f1 